name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Runs when you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Ruby for Jekyll (GitHub Pages uses Ruby)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Set Ruby version, adjust if needed

      # Step 3: Install Bundler (if not installed) and install dependencies from Gemfile
      - name: Install dependencies
        run: |
          gem install bundler  # Install Bundler (required for handling dependencies)
          # If Gemfile doesn't exist, create one with necessary contents
          echo "source 'https://rubygems.org'" > Gemfile
          echo "gem 'jekyll'" >> Gemfile
          echo "gem 'bundler'" >> Gemfile
          # Install all dependencies from the Gemfile
          bundle install

      # Step 4: Build the site with Jekyll (convert .md files into .html)
      - name: Build the site with Jekyll
        run: |
          bundle exec jekyll build  # Converts .md to .html and generates the site in _site/

      # Step 5: Deploy to GitHub Pages using the peaceiris actions-gh-pages action
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site  # Directory where Jekyll output is stored
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically use the GitHub token
