name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Runs when you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Ruby for Jekyll
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Set Ruby version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler  # Install Bundler
          bundle install       # Install dependencies from Gemfile

      # Step 4: Build the site with Jekyll
      - name: Build the site with Jekyll
        run: |
          bundle exec jekyll build  # Build the Jekyll site

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site  # Directory where Jekyll outputs the site
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for deployment
